// generated by https://app.quicktype.io/

import 'dart:convert';

List<Individual> individualsFromJson(String str) => List<Individual>.from(json.decode(str).map((x) => Individual.fromJson(x)));

Individual individualFromJson(String str) => Individual.fromJson(json.decode(str));

String individualsToJson(List<Individual> data) => json.encode(List<dynamic>.from(data.map((x) => x.toJson())));

class Individual {
    int id;
    String name;

    Individual({
        required this.id,
        required this.name,
    });

    factory Individual.fromJson(Map<String, dynamic> json) => Individual(
        id: json["id"],
        name: json["name"],
    );

    Map<String, dynamic> toJson() => {
        "id": id,
        "name": name,
    };
}