// generated by https://app.quicktype.io/
import 'dart:convert';


List<Location> locationsFromJson(String str) => List<Location>.from(json.decode(str).map((x) => Location.fromJson(x)));

Location locationFromJson(String str) => Location.fromJson(json.decode(str));

String locationToJson(Location data) => json.encode(data.toJson());

class Location {
    int? id;
    String name;
    List<int> preciseLocation;

    Location({
        this.id,
        required this.name,
        required this.preciseLocation,
    });

    factory Location.fromJson(Map<String, dynamic> json) => Location(
        id: json["id"],
        name: json["name"],
        preciseLocation: List<int>.from(json["precise_location"].map((x) => x)),
    );

    Map<String, dynamic> toJson() => {
        "id": id,
        "name": name,
        "precise_location": List<dynamic>.from(preciseLocation.map((x) => x)),
    };
}
