// generated by https://app.quicktype.io/

import 'dart:convert';
import 'package:salamander_tracker/models/individual.dart';
import 'package:salamander_tracker/models/location.dart';
import 'package:salamander_tracker/utils.dart';


List<Sighting> sightingsFromJson(String str) => List<Sighting>.from(json.decode(str).map((x) => Sighting.fromJson(x)));

Sighting sightingFromJson(String str) => Sighting.fromJson(json.decode(str));

class Sighting {
    int id;
    DateTime date;
    int individualId;
    String? individualName;
    Individual? individual;
    Location? location;

    Sighting({
        required this.id,
        required this.date,
        required this.individualId,
        required this.individualName,
        this.individual,
        this.location,
    });

    factory Sighting.fromJson(Map<String, dynamic> json) => Sighting(
        id: json["id"],
        date: parseDate(json["date"]),
        individualId: json["individual_id"],
        individualName: json["individual_name"],
        individual: json["individual"] == null ? null : Individual.fromJson(json["individual"]),
        location: json["location"] == null ? null : Location.fromJson(json["location"]),
    );

    Map<String, dynamic> toJson() => {
        "id": id,
        "date": date.toIso8601String(),
        "individual_id": individualId,
        "individual_name": individualName,
    };
}
