// generated by https://app.quicktype.io/

import 'dart:convert';

List<Sighting> sightingsFromJson(String str) => List<Sighting>.from(json.decode(str).map((x) => Sighting.fromJson(x)));

Sighting sightingFromJson(String str) => Sighting.fromJson(json.decode(str));

class Sighting {
    String id;
    DateTime date;
    String imageId;
    String individualId;
    String individualName;

    Sighting({
        required this.id,
        required this.date,
        required this.imageId,
        required this.individualId,
        required this.individualName,
    });

    factory Sighting.fromJson(Map<String, dynamic> json) => Sighting(
        id: json["_id"],
        date: DateTime.parse(json["date"]),
        imageId: json["image_id"],
        individualId: json["individual_id"],
        individualName: json["individual_name"],
    );

    Map<String, dynamic> toJson() => {
        "_id": id,
        "date": date.toIso8601String(),
        "image_id": imageId,
        "individual_id": individualId,
        "individual_name": individualName,
    };
}
